environment:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
packages:
  - name: llama_cpp-cpp
    actions:
      - name: perplexity
        runtime: 'python:default'
